---
title: "TITLE"
subtitle: "SUBTITLE"
author: "AUTHOR"
date: "`r format(Sys.Date(), '%d %b %Y')`"
# universal output options
number-sections: true
number-offset: 0
toc: true
toc-depth: 2
fig-width: 6
fig-height: 4
df-print: tibble
embed-resources: true
# format specific output options
format: 
  # html file
  html: 
    code-tools: true
    code-fold: show
    code-summary: "Show the code"
    toc-float: true
  # word file
  docx: 
    toc-title: "Table of contents"
    fig-dpi: 600
    execute:
      echo: false
# knitr global chunk options
knitr: 
  opts_chunk: 
    fig.path: "plots/"
    fig.keep: "all"
    dev: ['png', 'pdf']
    dev.args: 
      pdf: 
        encoding: 'WinAnsi'
        useDingbats: false
# bibliography and cross-references
bibliography: references.bib
crossref:
  fig-prefix: Fig.
  tbl-prefix: Table
  ref-hyperlink: true
# rstudio editor options
editor: source
editor_options: 
  chunk_output_type: console
---

# Setup

Using `r R.version.string` , @R, and tidyverse version `r packageVersion("tidyverse")`, @tidyverse.

```{r}
#| label: setup
#| message: false

# load packages
library(tidyverse)

# load scripts

```

# Data

```{r}
# load data
```

# Plots {#sec-plots}

@fig-example in section @sec-plots is a work of art.

## Heading 2

### Heading 3

```{r}
#| label: fig-example
#| fig-cap: Miles per gallon in city vs. highway driving for different car types.
#| fig-width: 5
#| fig-height: 3
ggplot(mpg) + 
  aes(x = hwy, y = cty, color = class) +
  geom_point()
```

# Tables

My @tbl-example is even more amazing.

```{r}
#| label: tbl-example
#| tbl-cap: This is my happy table, even has a beautiful equation $x^2 - \alpha$ 
#| tbl-cap-location: top
knitr::kable(head(mpg))
```

# References

::: {#refs}
:::
